"""add new product columns

Revision ID: 96311aca9a39
Revises: 99a574ed40d0
Create Date: 2026-04-18 21:40:31.238509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96311aca9a39'
down_revision: Union[str, Sequence[str], None] = '99a574ed40d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_orders', sa.Column('customer_address', sa.String(length=500), nullable=True))
    op.add_column('custom_orders', sa.Column('order_type', sa.String(length=100), nullable=True))
    op.add_column('custom_orders', sa.Column('deadline', sa.String(length=100), nullable=True))
    op.add_column('custom_orders', sa.Column('payment_method', sa.String(length=100), nullable=True))
    op.drop_column('custom_orders', 'category')
    op.add_column('order_items', sa.Column('image', sa.String(length=500), nullable=True))
    op.add_column('order_items', sa.Column('author', sa.String(length=200), nullable=True))
    op.add_column('order_items', sa.Column('school', sa.String(length=200), nullable=True))
    op.add_column('order_items', sa.Column('card_number', sa.String(length=50), nullable=True))
    op.add_column('order_items', sa.Column('student_type', sa.String(length=20), nullable=True))
    op.alter_column('order_items', 'qty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('orders', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('old_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('badge', sa.String(), nullable=True))
    op.add_column('products', sa.Column('author_ru', sa.String(), nullable=True))
    op.add_column('products', sa.Column('school_ru', sa.String(), nullable=True))
    op.add_column('products', sa.Column('grade', sa.String(), nullable=True))
    op.add_column('products', sa.Column('district_ru', sa.String(), nullable=True))
    op.add_column('products', sa.Column('region', sa.String(), nullable=True))
    op.add_column('products', sa.Column('region_ru', sa.String(), nullable=True))
    op.add_column('products', sa.Column('student_type', sa.String(), nullable=True))
    op.add_column('products', sa.Column('card_number', sa.String(), nullable=True))
    op.add_column('products', sa.Column('story_uz', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('story_ru', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('photo', sa.String(), nullable=True))
    op.add_column('products', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('reviews', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('sold', sa.Integer(), nullable=True))
    op.drop_column('products', 'class_uz')
    op.drop_column('products', 'class_ru')
    op.drop_column('products', 'is_new')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_new', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('class_ru', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('class_uz', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('products', 'sold')
    op.drop_column('products', 'reviews')
    op.drop_column('products', 'rating')
    op.drop_column('products', 'photo')
    op.drop_column('products', 'story_ru')
    op.drop_column('products', 'story_uz')
    op.drop_column('products', 'card_number')
    op.drop_column('products', 'student_type')
    op.drop_column('products', 'region_ru')
    op.drop_column('products', 'region')
    op.drop_column('products', 'district_ru')
    op.drop_column('products', 'grade')
    op.drop_column('products', 'school_ru')
    op.drop_column('products', 'author_ru')
    op.drop_column('products', 'badge')
    op.drop_column('products', 'old_price')
    op.drop_column('orders', 'note')
    op.drop_column('orders', 'city')
    op.alter_column('order_items', 'qty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('order_items', 'student_type')
    op.drop_column('order_items', 'card_number')
    op.drop_column('order_items', 'school')
    op.drop_column('order_items', 'author')
    op.drop_column('order_items', 'image')
    op.add_column('custom_orders', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('custom_orders', 'payment_method')
    op.drop_column('custom_orders', 'deadline')
    op.drop_column('custom_orders', 'order_type')
    op.drop_column('custom_orders', 'customer_address')
    # ### end Alembic commands ###
